;
; Windows Freenet Installer - Include file - Build info
;
; This file contains build info variables used for displaying info in the installer. These values should
; be updated by a build script before compiling the installer. Will be included directly into the
; installer (at the top) at compile time.
;
; _Inc_FreenetVersion - (string) Version of Freenet the installer contains.
; _Inc_FreenetBuild - (string) Build of Freenet the installer contains.
;

_Inc_FreenetVersion = 0.7.5
_Inc_FreenetBuild = #1223
